if Rails.env.production?
	TWITTER_CONSUMER_KEY = ENV['TWITTER_CONSUMER_KEY']
	TWITTER_CONSUMER_SECRET = ENV['TWITTER_CONSUMER_KEY']
else
  TWITTER_CONSUMER_KEY = "R9pa1sPFTsBNGRZPLLqqtA"
	TWITTER_CONSUMER_SECRET = "3NMAguFLZMrGGdgiFCGypX55PJ73qhhXrQqa7MI7TU4"
end

