if Rails.env.production?
	TWITTER_CONSUMER_KEY = ENV['TWITTER_CONSUMER_KEY']
	TWITTER_CONSUMER_SECRET = ENV['TWITTER_CONSUMER_KEY']
else
  TWITTER_CONSUMER_KEY = "Am1DYDJiFoautwZJ7MXcXg"
	TWITTER_CONSUMER_SECRET = "dTjN7CrRnk80gF5nj3nlchMbgpSkAHGji8SopUhwo"
end

